version: "3"
services:
  mongo:
    container_name: trello-mongo__test
    image: "mongo:4.2.7-bionic"
    logging:
      driver: none
    restart: never
  back:
    container_name: trello-back__test
    restart: never
    volumes:
      - ./back:/app
    build:
      context: ./back
      dockerfile: Dockerfile.test
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - "NODE_ENV=test"
      - "PORT=${API_PORT}"
      - "PASSWORD_SALT=${PASSWORD_SALT_DEV}"
      - "MONGO_URI=${MONGO_URI_TEST}"
      - "REDIS_URI=${REDIS_URI}"
      - "SESSION_SECRET=${SESSION_SECRET_DEV}"
    depends_on:
      - mongo
      - redis
  redis:
    container_name: trello-redis__test
    restart: never
    image: "redis:6.0.7-alpine"
    logging:
      driver: none
