version: "3"
services:
  mongo:
    container_name: trello-mongo
    image: "mongo:4.2.7-bionic"
    logging:
      driver: none

    volumes:
      - /data/db
    restart: unless-stopped
  back:
    container_name: trello-back
    restart: unless-stopped
    command: /app/entrypoint.sh
    volumes:
      - ./back:/app
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - "NODE_ENV=development"
      - "PORT=${API_PORT}"
      - "PASSWORD_SALT=${PASSWORD_SALT_DEV}"
      - "JWT_SECRET=${JWT_SECRET_DEV}"
      - "MONGO_URI=${MONGO_URI_DEV}"
      - "REDIS_URI=${REDIS_URI}"
      - "SESSION_SECRET=${SESSION_SECRET_DEV}"
    depends_on:
      - mongo
      - redis
  redis:
    container_name: trello-redis
    restart: unless-stopped
    image: "redis:6.0.7-alpine"
    volumes:
      - /data
