version: "3"
services:
  pg:
    container_name: trello-pg
    image: postgres
    restart: unless-stopped
    volumes:
      - /var/lib/postgresql/data
    environment: 
      - "POSTGRES_PASSWORD=${PG_PASSWORD_DEV}"
      - "POSTGRES_USER=${PG_USER_DEV}"
      - "POSTGRES_DB=${PG_DB_DEV}"
  back:
    container_name: trello-back
    restart: unless-stopped
    command: /app/entrypoint.sh
    volumes:
      - ./back:/app
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - "NODE_ENV=development"
      - "PORT=${API_PORT}"
      - "PG_PASSWORD=${PG_PASSWORD_DEV}"
      - "PG_USER=${PG_USER_DEV}"
      - "PG_DB=${PG_DB_DEV}"
      - "PG_HOST=pg"
      - "PASSWORD_SALT=${PASSWORD_SALT_DEV}"
      - "JWT_SECRET=${JWT_SECRET_DEV}"
    depends_on: 
      - pg
